### ISSUE TITLE
Trello: ToDo Dashboard

### ISSUE THREAD

**Issue by andreoliwa** [andreoliwa/dontforget#35]
After #28.
- [ ] Get the favorite Trello boards
- [ ] Get the first two lists from each board
- [ ] Show the cards in the dashboard
